_wandb:
    value:
        cli_version: 0.28.0
        e:
            1ycqtt5ra5anhyf1kbw926xpty7vu5gt:
                codePath: bcnet\utils\wandb_writer.py
                codePathLocal: bcnet\utils\wandb_writer.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "403396620288"
                        used: "249070321664"
                email: yana.zhang@studium.uni-hamburg.de
                executable: D:\Programs\miniconda3\envs\bcn_311\python.exe
                git:
                    commit: 05a3ca1f37fe64baddad99b51ba5c0066880bc55
                    remote: https://github.com/YN24601/Occluded-Object-Detection-using-Neural-Networks-BCNet-.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-0f94e733-7a2c-bd8e-23f4-dfd095512891
                host: YanaZLenovo
                memory:
                    total: "17083187200"
                os: Windows-10-10.0.26200-SP0
                program: d:\00workshop\pythonProjects\BCNet\bcnet\utils\wandb_writer.py
                python: CPython 3.11.15
                root: D:\00workshop\pythonProjects\BCNet
                startedAt: "2026-06-23T14:33:44.789607Z"
                writerId: 1ycqtt5ra5anhyf1kbw926xpty7vu5gt
        m: []
        python_version: 3.11.15
        t:
            "3":
                - 2
                - 16
            "4": 3.11.15
            "5": 0.28.0
            "8":
                - 3
            "12": 0.28.0
            "13": windows-amd64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
